version: '3.8'

services:
  daphne:
    container_name: daphne
    build:
      context: docker/
      dockerfile: daphne.dockerfile
    volumes:
      - daphne:/workdir/
    restart: on-failure

  nginx:
    container_name: nginx
    build:
      context: docker/
      dockerfile: nginx.dockerfile
      args:
        - DOMAIN=$DOMAIN
    env_file:
      - .env
    ports:
      - 443:443
    restart: on-failure

volumes:
  daphne:
    driver_opts:
      type: "none"
      o: "bind"
      device: /Users/ethaaalpha/42/ft_transcendance/