# Generated by Django 5.0.1 on 2024-01-22 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_2fa', models.BooleanField(default=False)),
                ('profile_picture', models.ImageField(blank=True, default='', upload_to='users/')),
                ('friends', models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL)),
                ('pending_friends_from', models.ManyToManyField(blank=True, related_name='pending_friends_from', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
