# Generated by Django 5.0.1 on 2024-01-29 16:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_profilepicture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blockedUsers',
            field=models.ManyToManyField(blank=True, related_name='blockedUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
