# Generated by Django 5.0.1 on 2024-01-29 19:25

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_blockedusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilePicture',
            field=models.ImageField(blank=True, default='default_e04bed5e-0be0-441b-9616-41f09b84aaf7.png', upload_to=users.models.generateUniqueImageID),
        ),
    ]
