# Generated by Django 5.0.1 on 2024-02-01 12:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lastPasswordChange',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
