# Generated by Django 5.0.1 on 2024-02-13 14:01

import django.db.models.deletion
import game.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to=settings.AUTH_USER_MODEL)),
                ('invited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('state', models.BooleanField(default=False)),
                ('id', models.CharField(default=game.models.roomIdGenerator, max_length=8, primary_key=True, serialize=False)),
                ('opponents', models.ManyToManyField(related_name='opponents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
