# Generated by Django 5.0.2 on 2024-02-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='matchs',
            field=models.ManyToManyField(related_name='matchs', to='game.match'),
        ),
    ]
